### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by jtieri** [jtieri/habbgo#17]
Creating this to serve as a checklist for myself as I wrap up some pieces of code that I've left unfinished in a local branch. 

Right now register/login works minus a few packets at login related to unsupported features e.g. habbo club, recycler, messenger, etc. Public rooms are loading with heightmaps and players are initialized so the next steps are getting the pathfinder implemented. Once that is complete the goal will likely be some hardcore cleanup and solidifying of designs before moving deep into the core of the games functionality. Better testing coverage would be nice as well so I may spend some time on that before moving on to other things.

- [ ] Finish high level design around room and player state
- [ ] Implement pathfinder
- [ ] Implement pathfinder commands/messages
- [ ] Cleanup sign in commands/messages to ensure SSO works and wrong passwords return proper packets
- [ ] Audit database related code. Possible refactor here or at least hardcore cleanup
- [ ] Cleanup entire codebase
- [ ] Possibly build out better test coverage (possible docker framework for simulating flows against live hotel)
